<a href="https://colab.research.google.com/github/ricadall/Basic-Numpy-and-Pandas/blob/main/HW2_Dallmann_Ricarda.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Homework 2**

### Create a copy of the notebook to start answering the questions. Name your notebook in the format HW2_lastname_firstname.ipynb to facilitate the grading process. 

### Answer all the questions, test your code to ensure there are no errors and the results are as expected. Once you have answered all the questions, save the final copy, then go to File-> click on Download.ipynb. Once the local copy has been downloaded, submit your file on Blackboard under the corresponding assignment section. Also provide us a link to your notebook during submission. 

### **The due date of this homework is 02/12/2021 (Friday).**

### Please ensure you follow all the steps mentioned in the homework.

### All the questions have a sample input and output to help you understand the question.

### You can submit your solutions any number of times until the deadline.


**Q1. Lets consider your data is like the below cell:**

**Q1-1**: Write a program that create a dataframe from the data.

**Q1-2:** Select people that are psychologist or teacher and their number of cars is greater than their family size.

**Q1-3:** Select people who have at most 2 family members and at least 1 car.

**Q1-4:** Write a code that get number of unique jobs in this dataset.





In [ ]:
data = {"name": ["Joseph", "Jacob", "Sam", "Jesee", "Ryan", "Lisa", "Lee"],
        "job": ["teacher", "psychologist", "data scientist", "software developer", "psychologist", "psychologist", "teacher"],
        "family_size": [3, 2, 1, 4, 2, 3, 2],
        "num_cars": [3, 1, 1, 2, 2, 4, 1]}

In [ ]:
data = {"name": ["Joseph", "Jacob", "Sam", "Jesee", "Ryan", "Lisa", "Lee"],
        "job": ["teacher", "psychologist", "data scientist", "software developer", "psychologist", "psychologist", "teacher"],
        "family_size": [3, 2, 1, 4, 2, 3, 2],
        "num_cars": [3, 1, 1, 2, 2, 4, 1]}
        
# Type your solution here
import pandas as pd

# Q1-1: Write a program that create a dataframe from the data.
frame = pd.DataFrame(data)

# Q1-2: Select people that are psychologist or teacher and their number of cars is greater than their family size.
frame[((frame["job"]== "psychologist") | (frame["job"]== "teacher")) & ( frame["num_cars"] > frame["family_size"])]

# Q1-3: Select people who have at most 2 family members and at least 1 car.
frame[(frame["family_size"] <= 2) & ( frame["num_cars"] >= 1)]

# Q1-4: Write a code that get number of unique jobs in this dataset.
unique_jobs = []
for job in frame["job"]:
  if not job in unique_jobs:
    unique_jobs.append(job)
print(len(unique_jobs))

4
['teacher', 'psychologist', 'data scientist', 'software developer']


**Q2. Lets consider you have two series like the below cell. Compute the mean of weights of each fruit.**

In [ ]:
import numpy as np
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))

In [ ]:
# problem:
import numpy as np
import pandas as pd
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))

# Type your solution here

joined = weights.groupby(fruit) # I discovered the groupby function on pandas.pydata.org (Link: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.groupby.html)
print("Means:")
joined.mean() # I discovered the mean function on pandas.pydata.org (Link: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.core.groupby.GroupBy.mean.html)


Means:


apple     6.5
banana    3.5
carrot    5.5
dtype: float64

**Q3. Consider the below course_name array:**

**Q3-1**: Write a NumPy program to get the indices of the sorted elements of **course_name** array.

**Q3-2:** Write numpy code to check whether each element of **course_name** array starts with "P".


In [ ]:
import numpy as np
course_name = np.array(['Python', 'JS', 'examples', 'PHP', 'html'])

In [ ]:
import numpy as np
course_name = np.array(['Python', 'JS', 'examples', 'PHP', 'html'])

# Type your solution here

# Q3-1: Write a NumPy program to get the indices of the sorted elements of course_name array.
print("Original array: ", course_name)
print("The indices of the sorted elements of course_name array:",np.argsort(course_name))

# Q3-2: Write numpy code to check whether each element of course_name array starts with "P"

# Solution #1 for Q3.2 (I did two solutions because I wasnt sure which way you wanted it to be presented, i.e as a list of booleans or just printed out)
p_start = True
for el in course_name:
  print(el, "starts with \"P\"", end = ": ")
  if el.startswith("P"):
    print("True")
  else:
    print("False")

# Solution #1 for Q3.2
print(np.char.startswith(course_name, "P")) # Note: I discovered the .char.startswith() function on datacamp


Original array:  ['Python' 'JS' 'examples' 'PHP' 'html']
The indices of the sorted elements of course_name array: [1 3 0 2 4]
Python starts with "P": True
JS starts with "P": False
examples starts with "P": False
PHP starts with "P": True
html starts with "P": False
[ True False False  True False]


**Q4. Consider the below student_id array:**

**Q4-1:** Reverse the **student_id** array. Print both original and reversed array.

**Q4-2:** Get the 3-largest values of **student_id** array.

In [ ]:
import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

In [ ]:
import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])
# Type your solution here

# Q4-1: Reverse the student_id array. Print both original and reversed array.
rev_student_id = np.flip(student_id, 0)
print("Original:", student_id)
print("Reversed:", rev_student_id)

# Q4-2: Get the 3-largest values of student_id array.
asc_student_id = np.sort(student_id)
desc_student_id = np.flip(asc_student_id, 0)
print("The 3-largest values of student_id array:", desc_student_id[:3])

Original: [1023 5202 6230 1671 1682 5241 4532]
Reversed: [4532 5241 1682 1671 6230 5202 1023]
The 3-largest values of student_id array: [6230 5241 5202]


# **Q5: Write a numpy program to print sum of all the multiples of 3 or 5 below 100**

In [ ]:
# Type your solution here
import numpy as np

arr = np.arange(1, 100) # get array from 1-99
# print(arr)

# make an array containing only multiples of 3 or 5
mult = arr[(arr % 5 == 0) | (arr % 3 == 0)]

# find sum of numbers in multi
sum = 0
for num in mult:
  sum += num
print(sum)


2318
2318


**Q6. Consider the below array.**

Q6.1. Write a code to swap column 1 with column 2.

Q6.2. Write a code to swap row 0 with row 1.

In [ ]:
import numpy as np

arr = np.arange(12).reshape(3,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
import numpy as np

arr = np.arange(12).reshape(3,4)
print("Original array:")
print(arr)

# Type your solution here

# Q6.1. Write a code to swap column 1 with column 2.
arr[:,[1, 2]] = arr[:,[2, 1]]
print("Array with when you swap column 1 with column 2:")
print(arr)

# Q6.2. Write a code to swap row 0 with row 1
arr[[0, 1],:] = arr[[1, 0],:]
print("Array with when you swap row 0 with row 1:")
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Array with when you swap column 1 with column 2:
[[ 0  2  1  3]
 [ 4  6  5  7]
 [ 8 10  9 11]]
Array with when you swap column 1 with column 2:
[[ 4  6  5  7]
 [ 0  2  1  3]
 [ 8 10  9 11]]
